name: Release

on:
  push:
    branches:
      - main
      - "next/**"
      - "rc/**"
      - "beta/**"
      - "alpha/**"
  workflow_dispatch:

jobs:
  release:
    name: Release / Node ${{ matrix.node }}
    strategy:
      matrix:
        node: ["20"]

    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - run: |
          npm ci

      - name: Create a release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PUSH_TOKEN }}
